[deploy]
bucket = 'jidecruddur-cloudformation'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://jidecruddur.site'
EnvBackendUrl = 'https://api.jidecruddur.site'
DDBMessageTable = 'CruddurDdb-DynamoDBTable-1P1F74EAZLIA0'