[deploy]
bucket = 'jidecruddur-cloudformation'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'jidegithub/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "jidecruddur-codepipeline-artifacts"
BuildSpec = 'backend-flask/buildspec.yml'
