[deploy]
bucket = 'jidecruddur-cloudformation'
region = 'us-east-1'
stack_name = 'CruddurCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CruddurCluster'
GitHubBranch = 'prod'
GithubRepo = 'jidegithub/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "jidecruddur-codepipeline-artifacts"
